AI.minimax JUnit test initially just adapt existing test JUnitTestAICreateGameTree.
Current stub fails because zero returned.

JUnitTestAICreateGameTree
JUnitTestAICreateGameTree
testTwoColsEmpty(JUnitTestAICreateGameTree)
java.lang.AssertionError: minimax unlikely to have propogated value zero
to the head
Expected: not <0>
     but: was <0>
	at ...